// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzU22K5HJEV06uU030Cl4RIElWMbk-I4M',
    appId: '1:1067551372434:web:bde6b7697e9d5671f3224b',
    messagingSenderId: '1067551372434',
    projectId: 'dsnanhospital',
    authDomain: 'dsnanhospital.firebaseapp.com',
    storageBucket: 'dsnanhospital.appspot.com',
    measurementId: 'G-C7C6MDGXLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3ekjfepDXNEhj92ZfNF_FfUNUc1Ai_1U',
    appId: '1:1067551372434:android:820e5bd7af89fdb1f3224b',
    messagingSenderId: '1067551372434',
    projectId: 'dsnanhospital',
    storageBucket: 'dsnanhospital.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIfUOm2l9AoEYswrj0f6eIc-bovV28HqU',
    appId: '1:1067551372434:ios:0f527c97a77b7e1df3224b',
    messagingSenderId: '1067551372434',
    projectId: 'dsnanhospital',
    storageBucket: 'dsnanhospital.appspot.com',
    iosBundleId: 'com.example.dScanHospital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIfUOm2l9AoEYswrj0f6eIc-bovV28HqU',
    appId: '1:1067551372434:ios:2f04f11d61a03d9cf3224b',
    messagingSenderId: '1067551372434',
    projectId: 'dsnanhospital',
    storageBucket: 'dsnanhospital.appspot.com',
    iosBundleId: 'com.example.dScanHospital.RunnerTests',
  );
}
